// types/Product.ts (update or keep existing)
export interface Product {
  id: string
  name: string
  brand: string
  category: string
  price: number
  originalPrice?: number
  discountPercentage?: number
  isNew?: boolean
  imageUrl: string
  description: string
  stock: number
}

// Mock Products Data
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '2',
    name: 'Smart Fitness Tracker',
    brand: 'FitTech',
    category: 'Wearables',
    price: 89.99,
    isNew: false,
    imageUrl: '/api/placeholder/300/300',
    description: 'Advanced fitness tracker with heart rate monitoring',
    stock: 100,
  },
  {
    id: '3',
    name: 'Portable Bluetooth Speaker',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 79.99,
    originalPrice: 99.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: 'Waterproof portable speaker with 12-hour battery life',
    stock: 75,
  },
  {
    id: '4',
    name: 'Smart Home Security Camera',
    brand: 'SecureTech',
    category: 'Smart Home',
    price: 129.99,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: '4K Ultra HD security camera with night vision',
    stock: 60,
  },
  {
    id: '5',
    name: 'Ergonomic Office Chair',
    brand: 'ComfortPro',
    category: 'Furniture',
    price: 249.99,
    originalPrice: 299.99,
    discountPercentage: 16,
    isNew: false,
    imageUrl: '/api/placeholder/300/300',
    description: 'Adjustable ergonomic chair with lumbar support',
    stock: 40,
  },
  {
    id: '6',
    name: 'Wireless Charging Pad',
    brand: 'PowerUp',
    category: 'Electronics',
    price: 39.99,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: 'Fast wireless charging pad compatible with multiple devices',
    stock: 200,
  },
  {
    id: '7',
    name: 'Premium Noise-Cancelling Earbuds',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 149.99,
    originalPrice: 189.99,
    discountPercentage: 21,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: 'True wireless earbuds with advanced noise cancellation',
    stock: 80,
  },
  {
    id: '8',
    name: 'Smart Robot Vacuum',
    brand: 'CleanTech',
    category: 'Smart Home',
    price: 299.99,
    originalPrice: 349.99,
    discountPercentage: 14,
    isNew: false,
    imageUrl: '/api/placeholder/300/300',
    description: 'AI-powered robot vacuum with mapping technology',
    stock: 30,
  },
  {
    id: '9',
    name: 'Fitness Yoga Mat',
    brand: 'FitTech',
    category: 'Fitness',
    price: 49.99,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: 'Non-slip, eco-friendly yoga mat with alignment markers',
    stock: 150,
  },
  {
    id: '100',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '11',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '12',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '13',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '14',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '15',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },
  {
    id: '16',
    name: 'Wireless Noise Cancelling Headphones',
    brand: 'SoundWave',
    category: 'Electronics',
    price: 199.99,
    originalPrice: 249.99,
    discountPercentage: 20,
    isNew: true,
    imageUrl: '/images/products/nikeshoe.jpg',
    description: 'Premium wireless headphones with advanced noise cancellation',
    stock: 50,
  },

  {
    id: '10',
    name: 'Smart LED Light Bulbs (4-Pack)',
    brand: 'LightPro',
    category: 'Smart Home',
    price: 69.99,
    originalPrice: 89.99,
    discountPercentage: 22,
    isNew: true,
    imageUrl: '/api/placeholder/300/300',
    description: 'Wi-Fi enabled LED bulbs with millions of color options',
    stock: 100,
  },
]
